# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AttributeAssignment_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AttributeAssignment(object):
    def setupUi(self, AttributeAssignment):
        AttributeAssignment.setObjectName("AttributeAssignment")
        AttributeAssignment.resize(570, 602)
        self.formLayout = QtWidgets.QFormLayout(AttributeAssignment)
        self.formLayout.setObjectName("formLayout")
        self.label_field = QtWidgets.QLabel(AttributeAssignment)
        self.label_field.setObjectName("label_field")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_field)
        self.label_value = QtWidgets.QLabel(AttributeAssignment)
        self.label_value.setObjectName("label_value")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_value)
        self.mMapLayerComboBox = gui.QgsMapLayerComboBox(AttributeAssignment)
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mMapLayerComboBox)
        self.label_layer = QtWidgets.QLabel(AttributeAssignment)
        self.label_layer.setObjectName("label_layer")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_layer)
        self.mFieldComboBox = gui.QgsFieldComboBox(AttributeAssignment)
        self.mFieldComboBox.setObjectName("mFieldComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.mFieldComboBox)
        self.mValuePlaceholder = QtWidgets.QWidget(AttributeAssignment)
        self.mValuePlaceholder.setObjectName("mValuePlaceholder")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mValuePlaceholder)

        self.retranslateUi(AttributeAssignment)
        QtCore.QMetaObject.connectSlotsByName(AttributeAssignment)

    def retranslateUi(self, AttributeAssignment):
        _translate = QtCore.QCoreApplication.translate
        AttributeAssignment.setWindowTitle(_translate("AttributeAssignment", "AttributeAssignment"))
        self.label_field.setText(_translate("AttributeAssignment", "Field"))
        self.label_value.setText(_translate("AttributeAssignment", "Value"))
        self.label_layer.setText(_translate("AttributeAssignment", "Layer"))
from qgis import gui
